# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('corpus_size', models.IntegerField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'config',
            },
        ),
        migrations.CreateModel(
            name='Negative',
            fields=[
                ('bigram', models.TextField(blank=True, db_index=True, primary_key=True, serialize=False, unique=True)),
                ('freq', models.IntegerField()),
            ],
            options={
                'db_table': 'negative',
            },
        ),
        migrations.CreateModel(
            name='Positive',
            fields=[
                ('bigram', models.TextField(blank=True, db_index=True, primary_key=True, serialize=False, unique=True)),
                ('freq', models.IntegerField()),
            ],
            options={
                'db_table': 'positive',
            },
        ),
        migrations.CreateModel(
            name='TestTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('screenname', models.TextField()),
                ('tweet', models.TextField()),
                ('pub_time', models.DateTimeField()),
            ],
        ),
    ]
