# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='age',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
